# url é‡Œå¡«å†™è‡ªå·±çš„è®¢é˜…,åç§°ä¸èƒ½é‡å¤
proxy-providers:
  provider1:
    url: ""  #""é‡Œå†™æœºåœºè®¢é˜…é“¾æ¥
    type: http
    interval: 86400
    health-check: {enable: true,url: "https://www.gstatic.com/generate_204",interval: 300}
    override:
      additional-prefix: "[]"  #[]é‡Œå†™æœºåœºå

  provider2:
    url: ""  #""é‡Œå†™æœºåœºè®¢é˜…é“¾æ¥
    type: http
    interval: 86400
    health-check: {enable: true,url: "https://www.gstatic.com/generate_204",interval: 300}
    override:
      additional-prefix: "[]"  #[]é‡Œå†™æœºåœºå

proxies: 
  - name: "ç›´è¿"
    type: direct
    udp: true

mixed-port: 7890
ipv6: true
allow-lan: true
unified-delay: false
tcp-concurrent: true
external-controller: 127.0.0.1:9090
external-ui: ui
external-ui-url: "https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip"

find-process-mode: strict
global-client-fingerprint: chrome

profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - "Mijia Cloud"
    - "+.push.apple.com"

tun:
  enable: true
  stack: mixed
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true

dns:
  enable: true
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-filter:
    - "*"
    - "+.lan"
    - "+.local"
    - "+.market.xiaomi.com"
  default-nameserver:
    - tls://223.5.5.5
    - tls://223.6.6.6
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query

proxy-groups:
  - name: å¥—é¤åˆ°æœŸ
    type: select
    include-all: true
    exclude-type: direct
    filter: "(?i)å¥—é¤åˆ°æœŸ"
    icon: https://gh-proxy.com/https://github.com/heywangchaochen/Qure/blob/master/IconSet/Color/Pirate_Nation.png

  - name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
    type: select
    proxies:
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
      - é¦™æ¸¯
      - å°æ¹¾
      - æ—¥æœ¬
      - æ–°åŠ å¡
      - ç¾å›½
      - å…¶å®ƒåœ°åŒº
      - DIRECT
    icon: https://gh-proxy.com/https://github.com/heywangchaochen/Qure/blob/master/IconSet/Color/Proxy.png

  - name: ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
    type: select
    include-all: true
    exclude-type: direct
    icon: https://gh-proxy.com/https://github.com/heywangchaochen/Qure/blob/master/IconSet/Color/WiFi.png

  - name: â™»ï¸ è‡ªåŠ¨é€‰æ‹© 
    type: url-test
    include-all: true
    exclude-type: direct
    tolerance: 10
    icon: https://gh-proxy.com/https://github.com/heywangchaochen/Qure/blob/master/IconSet/Color/Loop.png

  - name: ğŸ“² ç”µæŠ¥æ¶ˆæ¯
    type: select
    proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©,é¦™æ¸¯,å°æ¹¾,æ–°åŠ å¡,ç¾å›½,DIRECT]
    icon: https://gh-proxy.com/https://github.com/heywangchaochen/Qure/blob/master/IconSet/Color/Telegram.png

  - name: ğŸ’¬ Aiå¹³å°
    type: select
    proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©,å°æ¹¾,æ–°åŠ å¡,ç¾å›½,DIRECT]
    icon: https://gh-proxy.com/https://github.com/heywangchaochen/Qure/blob/master/IconSet/Color/ChatGPT.png

  - name: ğŸ“¹ æ²¹ç®¡è§†é¢‘
    type: select
    proxies: [ç¾å›½,ğŸš€ èŠ‚ç‚¹é€‰æ‹©,é¦™æ¸¯,å°æ¹¾,æ–°åŠ å¡,DIRECT]
    icon: https://gh-proxy.com/https://github.com/heywangchaochen/Qure/blob/master/IconSet/Color/YouTube.png

  - name: ğŸ¥ å¥ˆé£è§†é¢‘
    type: select
    proxies: [ç¾å›½,ğŸš€ èŠ‚ç‚¹é€‰æ‹©,é¦™æ¸¯,å°æ¹¾,æ–°åŠ å¡,DIRECT]
    icon: https://gh-proxy.com/https://github.com/heywangchaochen/Qure/blob/master/IconSet/Color/Netflix.png

  - name: ğŸµ TikTok
    type: select
    proxies:  [ç¾å›½,ğŸš€ èŠ‚ç‚¹é€‰æ‹©,é¦™æ¸¯,å°æ¹¾,æ–°åŠ å¡,DIRECT]
    icon: https://gh-proxy.com/https://github.com/heywangchaochen/Qure/blob/master/IconSet/Color/TikTok_1.png

  - name: ğŸŒ å›½å¤–åª’ä½“
    type: select
    proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©,é¦™æ¸¯,å°æ¹¾,æ–°åŠ å¡,ç¾å›½,DIRECT]
    icon: https://gh-proxy.com/https://github.com/heywangchaochen/Qure/blob/master/IconSet/Color/ForeignMedia.png

  - name: ğŸŒ å›½å†…åª’ä½“
    type: select
    proxies: [DIRECT]
    icon: https://gh-proxy.com/https://github.com/heywangchaochen/Qure/blob/master/IconSet/Color/Global.png

  - name: ğŸ“¢ è°·æ­ŒFCM
    type: select
    proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©,DIRECT]
    icon: https://gh-proxy.com/https://github.com/heywangchaochen/Qure/blob/master/IconSet/Color/Google_Search.png

  - name: ğŸªŸ å¾®è½¯æœåŠ¡
    type: select
    proxies: [DIRECT,ğŸš€ èŠ‚ç‚¹é€‰æ‹©,é¦™æ¸¯,å°æ¹¾,æ–°åŠ å¡,ç¾å›½,è‡ªå»ºèŠ‚ç‚¹]
    icon: https://gh-proxy.com/https://github.com/heywangchaochen/Qure/blob/master/IconSet/Color/Microsoft.png

  - name: ğŸ¯ å…¨çƒç›´è¿
    type: select
    proxies: [DIRECT]
    icon: https://gh-proxy.com/https://github.com/heywangchaochen/Qure/blob/master/IconSet/Color/Direct.png

  - name: ğŸ›‘ å¹¿å‘Šæ‹¦æˆª
    type: select
    proxies: [REJECT,DIRECT]
    icon: https://gh-proxy.com/https://github.com/heywangchaochen/Qure/blob/master/IconSet/Color/AdBlack.png

  - name: ğŸƒ åº”ç”¨å‡€åŒ–
    type: select
    proxies: [REJECT,DIRECT]
    icon: https://gh-proxy.com/https://github.com/heywangchaochen/Qure/blob/master/IconSet/Color/Azure.png

  - name: ğŸ›¡ï¸ éšç§é˜²æŠ¤
    type: select
    proxies: [REJECT,DIRECT]
    icon: https://gh-proxy.com/https://github.com/heywangchaochen/Qure/blob/master/IconSet/Color/Advertising.png

  - name: ğŸŸ æ¼ç½‘ä¹‹é±¼
    type: select
    proxies:  [ğŸš€ èŠ‚ç‚¹é€‰æ‹©,é¦™æ¸¯,å°æ¹¾,æ–°åŠ å¡,ç¾å›½,DIRECT]
    icon: https://gh-proxy.com/https://github.com/heywangchaochen/Qure/blob/master/IconSet/Color/Global.png

  #åˆ†éš”,ä¸‹é¢æ˜¯åœ°åŒºåˆ†ç»„
  - name: é¦™æ¸¯
    type: select
    include-all: true
    exclude-type: direct
    filter: "(?i)æ¸¯|hk|hongkong|hong kong"
    icon: https://gh-proxy.com/https://github.com/heywangchaochen/Qure/blob/master/IconSet/Color/Hong_Kong.png

  - name: å°æ¹¾
    type: select
    include-all: true
    exclude-type: direct
    filter: "(?i)å°|tw|taiwan"
    icon: https://gh-proxy.com/https://github.com/heywangchaochen/Qure/blob/master/IconSet/Color/Taiwan.png

  - name: æ—¥æœ¬
    type: select
    include-all: true
    exclude-type: direct
    filter: "(?i)æ—¥|jp|japan"
    icon: https://gh-proxy.com/https://github.com/heywangchaochen/Qure/blob/master/IconSet/Color/Japan.png

  - name: ç¾å›½
    type: select
    include-all: true
    exclude-type: direct
    filter: "(?i)ç¾|us|unitedstates|united states"
    icon: https://gh-proxy.com/https://github.com/heywangchaochen/Qure/blob/master/IconSet/Color/United_States.png

  - name: æ–°åŠ å¡
    type: select
    include-all: true
    exclude-type: direct
    filter: "(?i)(æ–°|sg|singapore)"
    icon: https://gh-proxy.com/https://github.com/heywangchaochen/Qure/blob/master/IconSet/Color/Singapore.png

  - name: å…¶å®ƒåœ°åŒº
    type: select
    include-all: true
    exclude-type: direct
    filter: "(?i)^(?!.*(?:ğŸ‡­ğŸ‡°|ğŸ‡¯ğŸ‡µ|ğŸ‡ºğŸ‡¸|ğŸ‡¸ğŸ‡¬|ğŸ‡¨ğŸ‡³|æ¸¯|hk|hongkong|å°|tw|taiwan|æ—¥|jp|japan|æ–°|sg|singapore|ç¾|us|unitedstates)).*"
    icon: https://gh-proxy.com/https://github.com/heywangchaochen/Qure/blob/master/IconSet/Color/Area.png


rules:
#Githubè§„åˆ™
  - RULE-SET,Global_Direct,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,Ad_Block,ğŸ›‘ å¹¿å‘Šæ‹¦æˆª
  - RULE-SET,Application_Purification,ğŸƒ åº”ç”¨å‡€åŒ–
  - RULE-SET,Privacy_Protection,ğŸ›¡ï¸ éšç§é˜²æŠ¤
  - RULE-SET,GoogleFCM,ğŸ“¢ è°·æ­ŒFCM
  - RULE-SET,Microsoft,ğŸªŸ å¾®è½¯æœåŠ¡
  - RULE-SET,Telegram,ğŸ“² ç”µæŠ¥æ¶ˆæ¯
  - RULE-SET,AI,ğŸ’¬ Aiå¹³å°
  - RULE-SET,YouTube,ğŸ“¹ æ²¹ç®¡è§†é¢‘
  - RULE-SET,Netflix,ğŸ¥ å¥ˆé£è§†é¢‘
  - RULE-SET,China,ğŸŒ å›½å†…åª’ä½“
  - RULE-SET,Foreign,ğŸŒ å›½å¤–åª’ä½“
  - RULE-SET,TikTok,ğŸµ TikTok
  - RULE-SET,Node_Selection,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - GEOIP,CN,DIRECT
  - MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼


rule-anchor:
  c: &c {type: http, interval: 86400, behavior: classical, format: text}
rule-providers:
  Global_Direct:
    <<: *c
    url: "https://raw.githubusercontent.com/heywangchaochen/Clash_Rules_Script/refs/heads/main/Rules/Global_Direct.list"
  Ad_Block:
    <<: *c
    url: "https://raw.githubusercontent.com/heywangchaochen/Clash_Rules_Script/refs/heads/main/Rules/Ad_Block.list"
  Application_Purification:
    <<: *c
    url: "https://raw.githubusercontent.com/heywangchaochen/Clash_Rules_Script/refs/heads/main/Rules/Application_Purification.list"
  Privacy_Protection:
    <<: *c
    url: "https://raw.githubusercontent.com/heywangchaochen/Clash_Rules_Script/refs/heads/main/Rules/Privacy_Protection.list"
  GoogleFCM:
    <<: *c
    url: "https://raw.githubusercontent.com/heywangchaochen/Clash_Rules_Script/refs/heads/main/Rules/GoogleFCM.list"
  Microsoft:
    <<: *c
    url: "https://raw.githubusercontent.com/heywangchaochen/Clash_Rules_Script/refs/heads/main/Rules/Microsoft.list"
  Telegram:
    <<: *c
    url: "https://raw.githubusercontent.com/heywangchaochen/Clash_Rules_Script/refs/heads/main/Rules/Telegram.list"
  AI:
    <<: *c
    url: "https://raw.githubusercontent.com/heywangchaochen/Clash_Rules_Script/refs/heads/main/Rules/AI.list"
  YouTube:
    <<: *c
    url: "https://raw.githubusercontent.com/heywangchaochen/Clash_Rules_Script/refs/heads/main/Rules/YouTube.list"
  Netflix:
    <<: *c
    url: "https://raw.githubusercontent.com/heywangchaochen/Clash_Rules_Script/refs/heads/main/Rules/Netflix.list"
  China:
    <<: *c
    url: "https://raw.githubusercontent.com/heywangchaochen/Clash_Rules_Script/refs/heads/main/Rules/China.list"
  Foreign:
    <<: *c
    url: "https://raw.githubusercontent.com/heywangchaochen/Clash_Rules_Script/refs/heads/main/Rules/Foreign.list"
  TikTok:
    <<: *c
    url: "https://raw.githubusercontent.com/heywangchaochen/Clash_Rules_Script/refs/heads/main/Rules/TikTok.list"
  Node_Selection:
    <<: *c
    url: "https://raw.githubusercontent.com/heywangchaochen/Clash_Rules_Script/refs/heads/main/Rules/Node_Selection.list"
