# url é‡Œå¡«å†™è‡ªå·±çš„è®¢é˜…,åç§°ä¸èƒ½é‡å¤
proxy-providers:
  provider1:
    url: "" #""é‡Œå†™æœºåœºè®¢é˜…é“¾æ¥
    type: http
    interval: 86400
    health-check: {enable: true,url: "https://www.gstatic.com/generate_204",interval: 300}
    override:
      additional-prefix: "[]" #[]é‡Œå†™æœºåœºå

  provider2:
    url: "" #""é‡Œå†™æœºåœºè®¢é˜…é“¾æ¥
    type: http
    interval: 86400
    health-check: {enable: true,url: "https://www.gstatic.com/generate_204",interval: 300}
    override:
      additional-prefix: "[]" #[]é‡Œå†™æœºåœºå

  provider3:
    url: "" #""é‡Œå†™æœºåœºè®¢é˜…é“¾æ¥
    type: http
    interval: 86400
    health-check: {enable: true,url: "https://www.gstatic.com/generate_204",interval: 300}
    override:
      additional-prefix: "[]" #[]é‡Œå†™æœºåœºå

  provider4:
    url: "" #""é‡Œå†™æœºåœºè®¢é˜…é“¾æ¥
    type: http
    interval: 86400
    health-check: {enable: true,url: "https://www.gstatic.com/generate_204",interval: 300}
    override:
      additional-prefix: "[]" #[]é‡Œå†™æœºåœºå

proxies: 
  - name: "å…¨çƒç›´è¿"
    type: direct
    udp: true

mixed-port: 7890
ipv6: true
allow-lan: true
unified-delay: false
tcp-concurrent: true
external-controller: 127.0.0.1:9090
external-ui: ui
external-ui-url: "https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip"

find-process-mode: strict
global-client-fingerprint: chrome

profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - "Mijia Cloud"
    - "+.push.apple.com"

tun:
  enable: true
  stack: mixed
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true

dns:
  enable: true
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-filter:
    - "*"
    - "+.lan"
    - "+.local"
    - "+.market.xiaomi.com"
  default-nameserver:
    - tls://223.5.5.5
    - tls://223.6.6.6
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query

proxy-groups:
  - name: å¥—é¤åˆ°æœŸ
    type: select
    include-all: true
    exclude-type: direct
    filter: "(?i)å¥—é¤åˆ°æœŸ|æµé‡"
    icon: https://gh-proxy.com/https://github.com/heywangchaochen/Qure/blob/master/IconSet/Color/Pirate_Nation.png

  - name: èŠ‚ç‚¹é€‰æ‹©
    type: select
    proxies:
      - æ‰‹åŠ¨åˆ‡æ¢
      - ğŸ‡­ğŸ‡° é¦™æ¸¯
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬
      - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡
      - ğŸ‡ºğŸ‡¸ ç¾å›½
      - å…¶å®ƒåœ°åŒº
      - è‡ªå»ºèŠ‚ç‚¹
      - DIRECT
    icon: https://gh-proxy.com/https://github.com/heywangchaochen/Qure/blob/master/IconSet/Color/Proxy.png

  - name: æ‰‹åŠ¨åˆ‡æ¢
    type: select
    include-all: true
    exclude-type: direct
    icon: https://gh-proxy.com/https://github.com/heywangchaochen/Qure/blob/master/IconSet/Color/WiFi.png

  - name: è‡ªåŠ¨é€‰æ‹© 
    type: url-test
    include-all: true
    exclude-type: direct
    tolerance: 10
    icon: https://gh-proxy.com/https://github.com/heywangchaochen/Qure/blob/master/IconSet/Color/Loop.png

  - name: Telegram
    type: select
    proxies: [èŠ‚ç‚¹é€‰æ‹©,ğŸ‡­ğŸ‡° é¦™æ¸¯,ğŸ‡¹ğŸ‡¼ å°æ¹¾,ğŸ‡¯ğŸ‡µ æ—¥æœ¬,ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡,ğŸ‡ºğŸ‡¸ ç¾å›½,å…¶å®ƒåœ°åŒº,è‡ªå»ºèŠ‚ç‚¹,DIRECT]
    icon: https://gh-proxy.com/https://github.com/heywangchaochen/Qure/blob/master/IconSet/Color/Telegram.png

  - name: AI
    type: select
    proxies: [èŠ‚ç‚¹é€‰æ‹©,ğŸ‡­ğŸ‡° é¦™æ¸¯,ğŸ‡¹ğŸ‡¼ å°æ¹¾,ğŸ‡¯ğŸ‡µ æ—¥æœ¬,ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡,ğŸ‡ºğŸ‡¸ ç¾å›½,å…¶å®ƒåœ°åŒº,è‡ªå»ºèŠ‚ç‚¹,DIRECT]
    icon: https://gh-proxy.com/https://github.com/heywangchaochen/Qure/blob/master/IconSet/Color/ChatGPT.png

  - name: Google
    type: select
    proxies: [èŠ‚ç‚¹é€‰æ‹©,ğŸ‡­ğŸ‡° é¦™æ¸¯,ğŸ‡¹ğŸ‡¼ å°æ¹¾,ğŸ‡¯ğŸ‡µ æ—¥æœ¬,ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡,ğŸ‡ºğŸ‡¸ ç¾å›½,å…¶å®ƒåœ°åŒº,è‡ªå»ºèŠ‚ç‚¹,DIRECT]
    icon: https://gh-proxy.com/https://github.com/heywangchaochen/Qure/blob/master/IconSet/Color/Google_Search.png

  - name: TikTok
    type: select
    proxies:  [èŠ‚ç‚¹é€‰æ‹©,ğŸ‡­ğŸ‡° é¦™æ¸¯,ğŸ‡¹ğŸ‡¼ å°æ¹¾,ğŸ‡¯ğŸ‡µ æ—¥æœ¬,ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡,ğŸ‡ºğŸ‡¸ ç¾å›½,å…¶å®ƒåœ°åŒº,è‡ªå»ºèŠ‚ç‚¹,DIRECT]
    icon: https://gh-proxy.com/https://github.com/heywangchaochen/Qure/blob/master/IconSet/Color/TikTok_1.png

  - name: YouTubeMusic
    type: select
    proxies: [èŠ‚ç‚¹é€‰æ‹©,ğŸ‡­ğŸ‡° é¦™æ¸¯,ğŸ‡¹ğŸ‡¼ å°æ¹¾,ğŸ‡¯ğŸ‡µ æ—¥æœ¬,ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡,ğŸ‡ºğŸ‡¸ ç¾å›½,å…¶å®ƒåœ°åŒº,è‡ªå»ºèŠ‚ç‚¹,DIRECT]
    icon: https://gh-proxy.com/https://github.com/heywangchaochen/Qure/blob/master/IconSet/Color/YouTube_Music.png
    
  - name: YouTube
    type: select
    proxies: [èŠ‚ç‚¹é€‰æ‹©,ğŸ‡­ğŸ‡° é¦™æ¸¯,ğŸ‡¹ğŸ‡¼ å°æ¹¾,ğŸ‡¯ğŸ‡µ æ—¥æœ¬,ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡,ğŸ‡ºğŸ‡¸ ç¾å›½,å…¶å®ƒåœ°åŒº,è‡ªå»ºèŠ‚ç‚¹,DIRECT]
    icon: https://gh-proxy.com/https://github.com/heywangchaochen/Qure/blob/master/IconSet/Color/YouTube.png

  - name: Netflix
    type: select
    proxies: [èŠ‚ç‚¹é€‰æ‹©,ğŸ‡­ğŸ‡° é¦™æ¸¯,ğŸ‡¹ğŸ‡¼ å°æ¹¾,ğŸ‡¯ğŸ‡µ æ—¥æœ¬,ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡,ğŸ‡ºğŸ‡¸ ç¾å›½,å…¶å®ƒåœ°åŒº,è‡ªå»ºèŠ‚ç‚¹,DIRECT]
    icon: https://gh-proxy.com/https://github.com/heywangchaochen/Qure/blob/master/IconSet/Color/Netflix.png
    
  - name: EmbyCF
    type: select
    proxies: [èŠ‚ç‚¹é€‰æ‹©,ğŸ‡­ğŸ‡° é¦™æ¸¯,ğŸ‡¹ğŸ‡¼ å°æ¹¾,ğŸ‡¯ğŸ‡µ æ—¥æœ¬,ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡,ğŸ‡ºğŸ‡¸ ç¾å›½,å…¶å®ƒåœ°åŒº,è‡ªå»ºèŠ‚ç‚¹,DIRECT]
    icon: https://gh-proxy.com/https://github.com/heywangchaochen/Qure/blob/master/IconSet/Color/Emby.png

  - name: å¹¿å‘Šæ‹¦æˆª
    type: select
    proxies: [REJECT,DIRECT]
    icon: https://gh-proxy.com/https://github.com/heywangchaochen/Qure/blob/master/IconSet/Color/AdBlack.png

  - name: åº”ç”¨å‡€åŒ–
    type: select
    proxies: [REJECT,DIRECT]
    icon: https://gh-proxy.com/https://github.com/heywangchaochen/Qure/blob/master/IconSet/Color/Azure.png
    
  - name: éšç§é˜²æŠ¤
    type: select
    proxies: [REJECT,DIRECT]
    icon: https://gh-proxy.com/https://github.com/heywangchaochen/Qure/blob/master/IconSet/Color/Advertising.png

  - name: å›½å†…åª’ä½“
    type: select
    proxies: [DIRECT]
    icon: https://gh-proxy.com/https://github.com/heywangchaochen/Qure/blob/master/IconSet/Color/Global.png

  - name: æ¼ç½‘ä¹‹é±¼
    type: select
    proxies:  [èŠ‚ç‚¹é€‰æ‹©,ğŸ‡­ğŸ‡° é¦™æ¸¯,ğŸ‡¹ğŸ‡¼ å°æ¹¾,ğŸ‡¯ğŸ‡µ æ—¥æœ¬,ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡,ğŸ‡ºğŸ‡¸ ç¾å›½,å…¶å®ƒåœ°åŒº,è‡ªå»ºèŠ‚ç‚¹,DIRECT]
    icon: https://gh-proxy.com/https://github.com/heywangchaochen/Qure/blob/master/IconSet/Color/Global.png

  #åˆ†éš”,ä¸‹é¢æ˜¯åœ°åŒºåˆ†ç»„
  - name: ğŸ‡­ğŸ‡° é¦™æ¸¯
    type: select
    include-all: true
    exclude-type: direct
    filter: "(?i)æ¸¯|hk|hongkong|hong kong"
    icon: https://gh-proxy.com/https://github.com/heywangchaochen/Qure/blob/master/IconSet/Color/Hong_Kong.png

  - name: ğŸ‡¹ğŸ‡¼ å°æ¹¾
    type: select
    include-all: true
    exclude-type: direct
    filter: "(?i)å°|tw|taiwan"
    icon: https://gh-proxy.com/https://github.com/heywangchaochen/Qure/blob/master/IconSet/Color/Taiwan.png

  - name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬
    type: select
    include-all: true
    exclude-type: direct
    filter: "(?i)æ—¥|jp|japan"
    icon: https://gh-proxy.com/https://github.com/heywangchaochen/Qure/blob/master/IconSet/Color/Japan.png

  - name: ğŸ‡ºğŸ‡¸ ç¾å›½
    type: select
    include-all: true
    exclude-type: direct
    filter: "(?i)ç¾|us|unitedstates|united states"
    icon: https://gh-proxy.com/https://github.com/heywangchaochen/Qure/blob/master/IconSet/Color/United_States.png

  - name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡
    type: select
    include-all: true
    exclude-type: direct
    filter: "(?i)(æ–°|sg|singapore)"
    icon: https://gh-proxy.com/https://github.com/heywangchaochen/Qure/blob/master/IconSet/Color/Singapore.png

  - name: å…¶å®ƒåœ°åŒº
    type: select
    include-all: true
    exclude-type: direct
    filter: "(?i)^(?!.*(?:ğŸ‡­ğŸ‡°|ğŸ‡¯ğŸ‡µ|ğŸ‡ºğŸ‡¸|ğŸ‡¸ğŸ‡¬|ğŸ‡¨ğŸ‡³|æ¸¯|hk|hongkong|å°|tw|taiwan|æ—¥|jp|japan|æ–°|sg|singapore|ç¾|us|unitedstates)).*"
    icon: https://gh-proxy.com/https://github.com/heywangchaochen/Qure/blob/master/IconSet/Color/Area.png

  - name: è‡ªå»ºèŠ‚ç‚¹
    type: select
    include-all: true
    exclude-type: direct
    filter: "(?i)è‡ªå»º"
    icon: https://gh-proxy.com/https://github.com/heywangchaochen/Qure/blob/master/IconSet/Color/Lock.png

rules:
#æ‰‹å†™è§„åˆ™åŒ¹é…

#Githubè§„åˆ™
  - RULE-SET,ad_block,å¹¿å‘Šæ‹¦æˆª
  - RULE-SET,application_purification,åº”ç”¨å‡€åŒ–
  - RULE-SET,youtube_domain,YouTube
  - RULE-SET,google_domain,Google
  - RULE-SET,telegram_domain,Telegram
  - RULE-SET,tiktok_domain,TikTok
  - RULE-SET,netflix_domain,Netflix
  - RULE-SET,twitch_domain,YouTube
  - RULE-SET,ai_domain,AI
  - RULE-SET,youtube_music_domain,YouTubeMusic
  - RULE-SET,spotify_domain,YouTubeMusic
  - RULE-SET,privacy_protection,éšç§é˜²æŠ¤
  - GEOIP,CN,DIRECT

  - RULE-SET,google_ip,Google
  - RULE-SET,netflix_ip,Netflix
  - RULE-SET,telegram_ip,Telegram
  - RULE-SET,cn_ip,DIRECT
  - MATCH,æ¼ç½‘ä¹‹é±¼

rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: mrs}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: mrs}
  c: &c {type: http, interval: 86400, behavior: classical, format: text}
rule-providers:
  ad_block:
    <<: *c
    url: "https://raw.githubusercontent.com/heywangchaochen/Clash_Rules_Script/blob/main/Rules/Ad_Block.list"
  application_purification:
    <<: *c
    url: "https://raw.githubusercontent.com/heywangchaochen/Clash_Rules_Script/blob/main/Rules/Application_Purification.list"
  youtube_domain:
    <<: *c
    url: "https://raw.githubusercontent.com/heywangchaochen/Clash_Rules_Script/refs/heads/main/Rules/YouTube.list"
  google_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs"
  telegram_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs"
  tiktok_domain:
    <<: *c
    url: "https://raw.githubusercontent.com/heywangchaochen/Clash_Rules_Script/refs/heads/main/Rules/TikTok.list"
  ai_domain:
    <<: *c
    url: "https://raw.githubusercontent.com/heywangchaochen/Clash_Rules_Script/refs/heads/main/Rules/AI.list"
  netflix_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.mrs"
  twitch_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/twitch.mrs"
  privacy_protection:
    <<: *c
    url: "https://raw.githubusercontent.com/heywangchaochen/Clash_Rules_Script/blob/main/Rules/Privacy_Protection.list"
  youtube_music_domain:
    type: http
    behavior: classical
    interval: 86400
    url: https://whatshub.top/rule/YouTubeMusic.rule
  spotify_domain:
    type: http
    behavior: classical
    interval: 86400
    url: https://whatshub.top/rule/Spotify.rule


  cn_ip:
    <<: *ip
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs"
  google_ip:
    <<: *ip
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.mrs"
  netflix_ip:
    <<: *ip
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.mrs"
  telegram_ip:
    <<: *ip
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.mrs"
